### ISSUE TITLE
Low Recall on Wiki Cohere Datset

### ISSUE THREAD

**Issue by john-wagster** [gaoj0017/RaBitQ#4]
I have been running some independent analysis of the RaBitQ paper and code and lack some intuition around why some datasets may fail.  I have a wikipedia dataset built using I believe a cohere v2 model that consistently gets low recall scores that I will link.  I believe the model requires using max inner product (MIP).  Would you be able to provide any intuition or guidance on how to adjust this implementation to better handle edge cases like with the cohere v2 model? 

Naively running the C code produces recall < 10% consistently.

We have also tried modifying the code based on foot note 8 from the paper and still get fairly low recall even with large numbers of clusters.  

https://huggingface.co/datasets/Cohere/wikipedia-22-12-simple-embeddings
I believe the model used to create it was the embed-multilingual-v2.0

Let me know if you need additional information happy to send additional artifacts if it would help better exemplify the low recall.  In general it's a very exciting approach and gets good overall recall on several of our test datasets.

**Comment by gaoj0017** [comment]
Thanks for your feedback. May I know more information about the low recall? Does it mean after re-ranking (based on the error bound), the method produces low recall or does it mean without re-ranking, it produces low recall? 

In addition, this code repo does not natively support MIP search. May I know how it is tested under the MIPS query?

**Comment by benwtrent** [comment]
@gaoj0017 the idea was simply using the estimator, but using inner-product instead of euclidean as the raw vector score.

For simplicity sake, only one coarse grained cluster was used. But here is one of the queries scores compared to the estimator value.

It seems that this estimator does a poor job in non-euclidean space. Here is a comparison of the same data set using inner-product vs. cosine vs. euclidean:

Inner-product (fairly poor):

![image](https://github.com/user-attachments/assets/272f9f29-d43b-49b0-b7f9-e0e78cd75ae0)

Cosine (a fairly nice correlation):

![image](https://github.com/user-attachments/assets/1be9c95d-ef3a-44f2-a92f-c3461d47759a)

Euclidean (excellent correlation):

![image](https://github.com/user-attachments/assets/9819e569-42dc-47b5-b5c6-a47004062b94)

**Comment by gaoj0017** [comment]
Does it mean that the figures are plotted by using exactly the same output of the estimated distance of the code repo (which is designed for estimating Euclidean distances) for estimating inner product and cosine similarity? 

If so, the method is not used in a correct way. Some minor modifications need to be made to support the estimation of inner product and cosine similarity. Would you mind posting the code for testing here?

**Comment by benwtrent** [comment]
> Does it mean that the figures are plotted by using exactly the same output of the estimated distance of the code repo (which is designed for estimating Euclidean distances) for estimating inner product and cosine similarity?

Yes, this was done strictly as an experiment. Basically, we wanted to see what vector spaces this estimator could represent.

>  Some minor modifications need to be made to support the estimation of inner product and cosine similarity.

This is what I expected. We opened this issue to indicate as much :). 

> Some minor modifications need to be made to support the estimation of inner product and cosine similarity.

As for supporting "cosine similarity", I wouldn't say that is strictly necessary. Requiring vectors to be normalized makes the estimator work well for dot-product/euclidean distance.

The tricky part is indeed inner-product, where the magnitude of the vector is important for the distance calculation.

> Would you mind posting the code for testing here?

Its very messy. Basically our goal was to replicate the paper's findings, which we did for all vector spaces. Cosine is easily supportable with the requirement that the cosine space enforces unit vectors, which means that dot-product & euclidean are roughly equivalent.

Its fairly simple to replicate directly by just downloading a couple 100k of https://huggingface.co/datasets/Cohere/wikipedia-22-12-simple-embeddings and comparing the estimator's results with true inner-product results.

**Comment by gaoj0017** [comment]
I see your points. Basically, the questions of estimating Euclidean distances and inner product are highly related to each other, but they are still different questions. Both of them can be supported with the core method of RaBitQ, but we cannot expect that directly using the estimator for one can produce a good estimated score for the other. 

Let me present how to support the estimation of inner product with the following equations. 
Let $\mathbf{o}_r$ and $\mathbf{q}_r$ be the raw data and query vectors. Let $\mathbf{c}$ be a centroid vector.
Let $\mathbf{o} = \frac{\mathbf{o}_r - \mathbf{c}}{||\mathbf{o}_r - \mathbf{c}||}$ be the normalized data vector. 

$\left< \mathbf{o}_r, \mathbf{q}_r\right> = \left< \mathbf{o}_r-\mathbf{c}, \mathbf{q}_r\right> + \left< \mathbf{c}, \mathbf{q}_r\right> =  ||\mathbf{o}_r-\mathbf{c}|| \cdot ||\mathbf{q}_r|| \left< \mathbf{o}, \frac{\mathbf{q}_r}{||\mathbf{q}_r||}\right> + \left< \mathbf{c}, \mathbf{q}_r\right>$

Here $||\mathbf{o}_r-\mathbf{c}||$ can be pre-computed. The computation of $||\mathbf{q}_r||$ and $\left< \mathbf{c}, \mathbf{q}_r\right>$ can be shared. Thus, the question is to estimate $\left< \mathbf{o}, \frac{\mathbf{q}_r}{||\mathbf{q}_r||}\right>$. This can be realized with RaBitQ.

**Comment by VoVAllen** [comment]
@gaoj0017 I had a different formula, are they the same? Is mine also viable for inner product?
![img_v3_02cn_859ffa92-6f25-4976-bb2b-9342b563380g](https://github.com/user-attachments/assets/9b5f2008-5fde-4bbb-8c04-b457a96eab7b)

**Comment by VoVAllen** [comment]
@gaoj0017 I had a different formula here, is this also viable?
![img_v3_02cn_859ffa92-6f25-4976-bb2b-9342b563380g](https://github.com/user-attachments/assets/f4846092-19e8-48ea-83b1-547d035db48f)

**Comment by gaoj0017** [comment]
@VoVAllen Yes. It is also viable. The formula I posted above does not normalize the query vector with respect to the centroid while this formula normalizes the query vector. I have not yet carefully studied for estimating inner product whether and how the normalization should be done. Possibly both formula are worth trying.

**Comment by john-wagster** [comment]
We were able to get a good implementation of this for MIP with good recall following the guidance here and footnote 8 from the paper.   We are now seeing recall for k=10, max rerank=50 of > 97% recall.  I really appreciate the help.  Our implementation does normalize the query vector with respect to the centroid.  We may try additional approaches in the future.  We are currently doing some scale evaluations.  I'll close this issue for now, but feel free to continue the conversation and we'll try to share details as we gain additional insights.

**Comment by gaoj0017** [comment]
Thanks for your update! If you have any further updates of evaluation/deployment or have any other questions, please don't hesitate to let me know.
