### ISSUE TITLE
A question of the distance comparison.

### ISSUE THREAD

**Issue by ZimingYuan** [gaoj0017/RaBitQ#6]
Hello! I'm a student studying ANN search and your idea and codes help me a lot. Now I have a question about the distance comparision implementation of your code. In `Line 104` of `src/ivf_rabitq.h`, I notice that you put accurate distance to the top-k heap instead of the estimate distance computed by RaBitQ. If I replace the accurate distance to the estimate distance, the recall drops significantly. Does it mean RaBitQ can only be used to roughly filter distances? Hope to get your answer.

**Comment by gaoj0017** [comment]
Yes. This version of RaBitQ only supports to roughly filter distances. For the version which supports higher accuracy, please refer to our new manuscript https://arxiv.org/abs/2409.09913. The code for the new version is available at https://github.com/VectorDB-NTU/Extended-RaBitQ.

**Comment by ZimingYuan** [comment]
Thanks for your reply. I'll check that.
